config/routes.rb
Rails.application.routes.draw do
  root 'beers#index'

  resources :beers, except: [:new]
  devise_for :users

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/beer.rb
class Beer < ApplicationRecord
  belongs_to :user
  validates_presence_of :name, :abw, :style
  # new -before_initialize
  # after new - after_initialize
  # before_save
  # after_save
  before_validation :random_beer

  private
    def random_beer
      if self.new_record?
      self.name = Faker::Beer.name
      self.style = Faker::Beer.style
      self.abw = Faker::Beer.alcohol
    end
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

         has_many :beers
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/beers_controller.rb
class BeersController < ApplicationController
  before_action :set_beer, only: [:show, :edit, :update, :destroy]

  # GET /beers
  # GET /beers.json
  def index
    @beers = current_user.beers
    @non_empty = @beers.where('empty = ?', false)
  end

  # GET /beers/1
  # GET /beers/1.json
  def show

  end


  # GET /beers/1/edit
  def edit
  end

  # POST /beers
  # POST /beers.json
  def create
    @beer = current_user.beers.new

    respond_to do |format|
      if @beer.save
        format.html { redirect_to beers_path, success: 'Here you go!' }
        format.json { render :show, status: :created, location: @beer }
      else
        format.html { render :new }
        format.json { render json: @beer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /beers/1
  # PATCH/PUT /beers/1.json
  def update
    respond_to do |format|
      if @beer.update(beer_params)
        format.html { redirect_to @beer, notice: 'Beer was successfully updated.' }
        format.json { render :show, status: :ok, location: @beer }
      else
        format.html { render :edit }
        format.json { render json: @beer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /beers/1
  # DELETE /beers/1.json
  def destroy
    @beer.destroy
    respond_to do |format|
      format.html { redirect_to beers_url, notice: 'Beer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_beer
      @beer = current_user.beers.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def beer_params
      params.require(:beer).permit(:name, :style, :empty, :abw)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/beers_helper.rb
module BeersHelper
end

app/views/beers/_form.html.erb
<%= form_for(beer) do |f| %>
  <% if beer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(beer.errors.count, "error") %> prohibited this beer from being saved:</h2>

      <ul>
      <% beer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.label :name %>
  <%= f.text_field :name %>
  <br />

  <%= f.label :style %>
  <%= f.text_field :style %>
  <br />

  <%= f.label :abw %>
  <%= f.text_field :abw %>
  <br />

  <%= f.label :empty %>
  <%= f.select :empty, ['true', 'false'], {}, class: 'browser-default' %>
  <br />

  <div class="actions">
    <%= f.submit nil, class: 'btn' %>
  </div>
<% end %>

app/views/beers/edit.html.erb
<h1>Editing Beer</h1>

<%= render 'form', beer: @beer %>

<%= link_to 'Show', @beer %> |
<%= link_to 'Back', beers_path %>

app/views/beers/new.html.erb
<h1>New Beer</h1>

<%= render 'form', beer: @beer %>

<%= link_to 'Back', beers_path %>

app/views/beers/show.html.erb
<div class='card'>
  <h3> <%= @beer.name %> </h3>
  <i> Style: <%= @beer.style %> </i>
  <br />
  <i> Alcohol By Weight: <%= @beer.abw %> </i>
  <br />
  <i> Style: <%= @beer.style %> </i>
  <br />
  <i>
    Empty?: <%= @beer.empty ? 'Oh no, grab another beer' : 'You need a nipple for that?' %>
  </i>
</div>

<hr />
<%= link_to 'Edit', edit_beer_path(@beer) %> |
<%= link_to 'Back', beers_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UserBeers</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <% flash.each do |type, message| %>
        <div class='flash <%= type %>'
          <%= message %>
        </div>
    <% end %>
    <div class='container'>
      <%= yield %>
    </div>
  </body>
</html>